#SPDX-License-Identifier: MIT-0
---
- name: Deploy Nethermind Ethereum Node
  hosts: eth-node-2
  become: true
  vars:
    # Network configuration
    nethermind_network: "mainnet"  # Options: mainnet, goerli, sepolia, etc.
    nethermind_sync_mode: "Fast"
    nethermind_fast_sync: true
    nethermind_fast_blocks: true
    
    # RPC configuration
    nethermind_enable_public_access: false
    nethermind_http_modules:
      - "Eth"
      - "Net"
      - "Web3"
      - "Debug"
      - "Trace"
      - "TxPool"
      - "Parity"
      - "Health"
      - "Rpc"
    
    nethermind_ws_modules:
      - "Eth"
      - "Net"
      - "Web3"
      - "Debug"
      - "Trace"
      - "TxPool"
      - "Parity"
      - "Health"
      - "Rpc"
    
    # Logging
    nethermind_log_level: "Info"
    
    # Metrics
    nethermind_metrics_enabled: true
    nethermind_metrics_port: 6060
  
  pre_tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
  
  roles:
    - role: deploy_nethermind_node
      tags: ['nethermind', 'deploy']
  
  post_tasks:
    - name: Display deployment information
      debug:
        msg:
          - "Nethermind node deployment complete!"
          - "P2P Port: {{ nethermind_p2p_port }}"
          - "HTTP RPC: http://{{ ansible_default_ipv4.address }}:{{ nethermind_http_port }}"
          - "WebSocket: ws://{{ ansible_default_ipv4.address }}:{{ nethermind_ws_port }}"
          - "Metrics: http://{{ ansible_default_ipv4.address }}:{{ nethermind_metrics_port }}/metrics"
          - "Data directory: {{ nethermind_data_dir }}"
          - "Configuration directory: {{ nethermind_config_dir }}"
      when: nethermind_metrics_enabled
    
    - name: Display deployment information (without metrics)
      debug:
        msg:
          - "Nethermind node deployment complete!"
          - "P2P Port: {{ nethermind_p2p_port }}"
          - "HTTP RPC: http://{{ ansible_default_ipv4.address }}:{{ nethermind_http_port }}"
          - "WebSocket: ws://{{ ansible_default_ipv4.address }}:{{ nethermind_ws_port }}"
          - "Data directory: {{ nethermind_data_dir }}"
          - "Configuration directory: {{ nethermind_config_dir }}"
      when: not nethermind_metrics_enabled
