#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Felix Serang 
  description: Deploy Ethereum Geth node with Docker
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - ethereum
    - blockchain
    - docker
    - geth
